from cli import generate_toml
from flask import Flask, Response
import requests

app = Flask(__name__)
app.config.from_object("config.BaseConfig")

@app.route("/")
def index():
    content_auto = generate_toml()

    template_url = app.config["TEMPLATE_URL"]
    if template_url:
        r = requests.get(template_url)
        content_tmpl = r.text
        content = content_tmpl.replace("{{AUTOGENERATED}}", content_auto)
    else:
        content = content_auto

    # Supposed to be application/toml, but would rather it render in browser
    # instead of downloading file.
    # See: https://github.com/toml-lang/toml/issues/465#issuecomment-364506403
    return Response(content, mimetype="text/toml")

if __name__ == "__main__":
    app.run()
