[general]
RemoteNickFormat="{NICK} ({CHANNEL}@{BRIDGE}): "
TranslationAttribution=" [translated by :google:]"
IgnoreNicks="slackbot"

## ACCOUNTS

#[slack.example]
##Token to connect with the Slack API
##You'll have to use a test/api-token using a dedicated user and not a bot token.
##See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
#Token="${SLACK_EXAMPLE_TOKEN}" # real user

[slack.civictechto]
# Token="${SLACK_CIVICTECHTO_TOKEN}" # bot user # set in envvar
ShowJoinPart=true

[slack.g0v-tw]
# Token="${SLACK_G0VTW_TOKEN}" # real user: bridgebot-patcon # set in envvar
# Too noisy. Related: https://github.com/42wim/matterbridge/issues/524
ShowJoinPart=false

[irc.irc]
Server="chat.freenode.net:6697"
Nick="g0v-bridgebot"
RemoteNickFormat="{NICK}@{PROTOCOL}: "
UseTLS=true
UseSASL=true
# NickServNick="${IRC_USERNAME}" # set in envvar
# NickServPassword="${IRC_PASSWORD}" # set in envvar

[telegram.telegram]
# Token="${TELEGRAM_TOKEN}" # bot user: hacklabto_bridgebot # set in envvar
RemoteNickFormat="{NICK}@{PROTOCOL}: "
UseInsecureURL=true

## GATEWAYS & BRIDGES

{{AUTOGENERATED}}
